# Generated by Django 3.0.8 on 2020-07-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planting',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seedpacket',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
