# Generated by Django 3.0.8 on 2020-07-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200719_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedpacket',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
