# Generated by Django 3.0.8 on 2020-08-23 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seedpacket_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultivar',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='common_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name='PlantingNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Planting')),
            ],
        ),
    ]
