# Generated by Django 3.1.7 on 2021-03-31 01:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200823_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultivar',
            options={'ordering': ['category__common_name', 'name']},
        ),
        migrations.AddField(
            model_name='planting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PlantingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planting')),
            ],
        ),
    ]
