# Generated by Django 4.2.4 on 2024-01-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_alter_plantingimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planting',
            options={'ordering': ['-active', '-date', 'seed']},
        ),
        migrations.AlterModelOptions(
            name='seedpacket',
            options={'ordering': ['-active', '-date', 'cultivar'], 'verbose_name_plural': 'Seed packets'},
        ),
        migrations.AddField(
            model_name='cultivar',
            name='aliases',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='PlantingNote',
        ),
    ]
