# Generated by Django 4.2.4 on 2024-08-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_seedpacket_url_alter_cultivar_aliases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seedsource',
            options={'ordering': ['name'], 'verbose_name_plural': 'Seed sources'},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
